### ISSUE TITLE
[Good Practice] Covers

### ISSUE THREAD

**Issue by PonyLucky** [PonyLucky/Pony-s-Manga-Manager#8]
Actually, we store the images in Base64 directly in mangaHistory in localStorage. This is not a good practice as the js output after save is heavy.

Here's a solution:
```plain
store cover's urls in js and main localStorage var.

Then store in another var (like 'mangaCovers') the base64 of the image.

If not found in mangaCovers, then fetch base64 and store it.
```

**Comment by PonyLucky** [comment]
Right, I didn't explain why I get more data than used (covers included).

Actually the app's working but it's ugly, so I thinking of getting something along this app:
https://valos.gitlab.io/Komikku/.

Apart from the fact that I don't see the usefulness to "download" chapters for web extension...

Anyway, I got all the data so just need to work on the front and it's done.

PS:
I didn't think someone would be interested in this extension in the current state of development.
@002love If you want to communicate to share your thoughts or anything, please don't fret to create an issue. I can enable the 'discussion' tab if you think it's more fitting.

I won't mind just sharing our favourite manga ;D

**Comment by 002love** [comment]
In fact, it's quite interesting to watch the creation and updating of something new. I think that your extension has a huge potential, because it makes it quite easy to read everyone's favorite manga. ^.^

**Comment by 002love** [comment]
I am also a react developer, so I can help move the page of your extension to react (if necessary) for faster work.
